version: "3.7"

# See https://stackoverflow.com/questions/29261811/use-docker-compose-env-variable-in-dockerbuild-file
services:
  webui:
    build:
      context: ./webui
      dockerfile: Dockerfile.dev
      args: # from env_file
        IMAGE_REPOSITORY: ${IMAGE_REPOSITORY}
        PROXY_USER: ${PROXY_USER}
        PROXY_PASSWORD: ${PROXY_PASSWORD}
        PROXY_FQDN: ${PROXY_FQDN}
        PROXY_PORT: ${PROXY_PORT}
    env_file:
      - .env
    container_name: webui-dev
    security_opt:
      - no-new-privileges:true    
    ports:
      - "8080:3000"
    volumes:
      - ./webui:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
      
  mongodb:
    build:
      context: ./mongodb
      dockerfile: Dockerfile.dev
      args: # from env_file
        IMAGE_REPOSITORY: ${IMAGE_REPOSITORY}
        PROXY_USER: ${PROXY_USER}
        PROXY_PASSWORD: ${PROXY_PASSWORD}
        PROXY_FQDN: ${PROXY_FQDN}
        PROXY_PORT: ${PROXY_PORT}
    env_file:
      - .env
    container_name: mongodb-dev      
    ports:
      - "28016:27017"
    volumes:
      - ./mongodb:/app
      - ./mongodb/scripts/init/:/docker-entrypoint-initdb.d
      - ./mongodb/scripts/init/:/home/mongodb
      - ./mongodb/scripts/seed/:/home/mongodb/seed
      - /app/node_modules      
      - mongodb-dev-data:/data/db
  
volumes:
  mongodb-dev-data:  
